-- Firearms Vault sync-safety migration
-- Apply in the Supabase SQL editor before deploying the matching client.

begin;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

-- A verified MFA factor makes AAL2 mandatory for that account. Defining this
-- before the CAS RPC lets the security-definer function enforce MFA itself.
create or replace function private.session_meets_opt_in_mfa()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, pg_temp
as $$
  select case
    when exists (
      select 1 from auth.mfa_factors
      where user_id = (select auth.uid()) and status = 'verified'
    ) then coalesce((select auth.jwt()->>'aal'), 'aal1') = 'aal2'
    else coalesce((select auth.jwt()->>'aal'), 'aal1') in ('aal1', 'aal2')
  end;
$$;
revoke all on function private.session_meets_opt_in_mfa() from public, anon, authenticated;
grant execute on function private.session_meets_opt_in_mfa() to authenticated;

alter table public.collections add column if not exists revision bigint not null default 0;
alter table public.collections add column if not exists media_manifest jsonb not null default '{}'::jsonb;
revoke all on public.collections from anon;
revoke insert, update, delete on public.collections from authenticated;
grant select on public.collections to authenticated;
drop policy if exists "collections_insert_own" on public.collections;
drop policy if exists "collections_update_own" on public.collections;
drop policy if exists "collections_delete_own" on public.collections;

create table if not exists public.collection_versions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  revision bigint not null,
  data jsonb not null,
  media_manifest jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (user_id, revision)
);
create index if not exists collection_versions_user_revision_idx
  on public.collection_versions (user_id, revision desc);
alter table public.collection_versions enable row level security;
revoke all on public.collection_versions from anon, authenticated;
grant select on public.collection_versions to authenticated;
drop policy if exists "collection_versions_select_own" on public.collection_versions;
create policy "collection_versions_select_own" on public.collection_versions
  for select to authenticated using (auth.uid() = user_id);
drop policy if exists "collection_versions_insert_own" on public.collection_versions;
drop policy if exists "collection_versions_delete_own" on public.collection_versions;

create or replace function public.save_collection_cas(
  p_expected_revision bigint,
  p_new_data jsonb,
  p_new_media_manifest jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = pg_catalog, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_current public.collections%rowtype;
  v_saved public.collections%rowtype;
begin
  if v_uid is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;
  if not private.session_meets_opt_in_mfa() then
    raise exception 'Complete multi-factor authentication before saving' using errcode = '42501';
  end if;
  if p_expected_revision is null or p_expected_revision < 0 then
    raise exception 'Expected revision must be zero or greater' using errcode = '22023';
  end if;
  if p_new_data is null or jsonb_typeof(p_new_data) <> 'object' then
    raise exception 'Collection data must be a JSON object' using errcode = '22023';
  end if;
  if p_new_media_manifest is null or jsonb_typeof(p_new_media_manifest) <> 'object' then
    raise exception 'Media manifest must be a JSON object' using errcode = '22023';
  end if;

  select c.* into v_current from public.collections as c
  where c.user_id = v_uid for update;

  if not found then
    if p_expected_revision <> 0 then
      return jsonb_build_object('status', 'conflict', 'revision', 0,
        'updated_at', null, 'data', '{}'::jsonb, 'media_manifest', '{}'::jsonb);
    end if;
    insert into public.collections (user_id, data, revision, media_manifest, updated_at)
    values (v_uid, p_new_data, 1, p_new_media_manifest, now())
    on conflict (user_id) do nothing returning * into v_saved;
    if not found then
      select c.* into v_current from public.collections as c where c.user_id = v_uid;
      return jsonb_build_object('status', 'conflict', 'revision', v_current.revision,
        'updated_at', v_current.updated_at, 'data', v_current.data,
        'media_manifest', v_current.media_manifest);
    end if;
  elsif v_current.revision <> p_expected_revision then
    return jsonb_build_object('status', 'conflict', 'revision', v_current.revision,
      'updated_at', v_current.updated_at, 'data', v_current.data,
      'media_manifest', v_current.media_manifest);
  else
    insert into public.collection_versions (user_id, revision, data, media_manifest, created_at)
    values (v_uid, v_current.revision, v_current.data, v_current.media_manifest, v_current.updated_at)
    on conflict (user_id, revision) do nothing;
    update public.collections as c
    set data = p_new_data, media_manifest = p_new_media_manifest,
        revision = c.revision + 1, updated_at = now()
    where c.user_id = v_uid returning c.* into v_saved;
  end if;

  delete from public.collection_versions as old
  where old.user_id = v_uid and old.id not in (
    select keep.id from public.collection_versions as keep
    where keep.user_id = v_uid order by keep.revision desc limit 50
  );
  return jsonb_build_object('status', 'saved', 'revision', v_saved.revision,
    'updated_at', v_saved.updated_at, 'data', v_saved.data,
    'media_manifest', v_saved.media_manifest);
end;
$$;
revoke all on function public.save_collection_cas(bigint, jsonb, jsonb) from public, anon, authenticated;
grant execute on function public.save_collection_cas(bigint, jsonb, jsonb) to authenticated;

create table if not exists public.health_checks (
  user_id uuid primary key references auth.users(id) on delete cascade,
  checked_at timestamptz not null default now(),
  source text not null default 'unknown'
);
alter table public.health_checks enable row level security;
revoke all on public.health_checks from anon, authenticated;
drop policy if exists "health_checks_own" on public.health_checks;
create policy "health_checks_own" on public.health_checks
  for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

create or replace function public.run_health_check_canary(p_source text default 'scheduled')
returns jsonb
language plpgsql
volatile
security definer
set search_path = pg_catalog, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_checked_at timestamptz := clock_timestamp();
  v_deleted bigint := 0;
begin
  if v_uid is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  insert into public.health_checks (user_id, checked_at, source)
  values (v_uid, v_checked_at, left(coalesce(nullif(p_source, ''), 'scheduled'), 80))
  on conflict (user_id) do update set checked_at = excluded.checked_at, source = excluded.source;
  delete from public.health_checks where user_id = v_uid;
  get diagnostics v_deleted = row_count;
  return jsonb_build_object('ok', v_deleted = 1, 'checked_at', v_checked_at, 'deleted', v_deleted);
end;
$$;
revoke all on function public.run_health_check_canary(text) from public, anon, authenticated;
grant execute on function public.run_health_check_canary(text) to authenticated;

commit;
