-- Share, MFA, and privacy hardening for the Firearms Vault.
-- Apply after 20260720000001_sync_safety.sql.

begin;

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;
do $$
declare current_schema text;
begin
  select n.nspname into current_schema
  from pg_catalog.pg_extension as e
  join pg_catalog.pg_namespace as n on n.oid = e.extnamespace
  where e.extname = 'pgcrypto';
  if current_schema is distinct from 'extensions' then
    execute 'alter extension pgcrypto set schema extensions';
  end if;
end;
$$;

create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated;

-- Users who opt in to MFA must present an AAL2 JWT. Users without a verified
-- factor can continue with AAL1, so the rollout does not lock out old accounts.
create or replace function private.session_meets_opt_in_mfa()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, pg_temp
as $$
  select case
    when exists (
      select 1 from auth.mfa_factors
      where user_id = (select auth.uid()) and status = 'verified'
    ) then coalesce((select auth.jwt()->>'aal'), 'aal1') = 'aal2'
    else coalesce((select auth.jwt()->>'aal'), 'aal1') in ('aal1', 'aal2')
  end;
$$;
revoke all on function private.session_meets_opt_in_mfa() from public, anon, authenticated;
grant execute on function private.session_meets_opt_in_mfa() to authenticated;

drop policy if exists "collections_mfa_opt_in" on public.collections;
create policy "collections_mfa_opt_in" on public.collections
  as restrictive for all to authenticated
  using (private.session_meets_opt_in_mfa())
  with check (private.session_meets_opt_in_mfa());

drop policy if exists "collection_versions_mfa_opt_in" on public.collection_versions;
create policy "collection_versions_mfa_opt_in" on public.collection_versions
  as restrictive for all to authenticated
  using (private.session_meets_opt_in_mfa())
  with check (private.session_meets_opt_in_mfa());

alter table public.shares add column if not exists access_code_hash text;
alter table public.shares add column if not exists max_views integer;
alter table public.shares add column if not exists access_count bigint not null default 0;
alter table public.shares add column if not exists last_accessed_at timestamptz;
alter table public.shares add column if not exists revoked_at timestamptz;
alter table public.shares add column if not exists has_access_code boolean
  generated always as (access_code_hash is not null) stored;

-- Normalize any pre-release test rows before validating the constraint.
update public.shares set max_views = null where max_views is not null and max_views <= 0;

do $$ begin
  alter table public.shares add constraint shares_max_views_positive
    check (max_views is null or max_views > 0);
exception when duplicate_object then null; end $$;

create index if not exists shares_owner_created_idx on public.shares (owner, created_at desc);
create index if not exists shares_expiry_idx on public.shares (expires_at) where expires_at is not null;

revoke all on public.shares from anon, authenticated;
grant select (token, owner, label, created_at, expires_at, max_views, access_count,
  last_accessed_at, revoked_at, has_access_code) on public.shares to authenticated;
grant delete on public.shares to authenticated;

drop policy if exists "shares_insert_own" on public.shares;
drop policy if exists "shares_update_own" on public.shares;
drop policy if exists "shares_mfa_opt_in" on public.shares;
create policy "shares_mfa_opt_in" on public.shares
  as restrictive for all to authenticated
  using (private.session_meets_opt_in_mfa())
  with check (private.session_meets_opt_in_mfa());

create table if not exists public.share_access_events (
  id bigint generated by default as identity primary key,
  share_token uuid not null references public.shares(token) on delete cascade,
  owner uuid not null references auth.users(id) on delete cascade,
  accessed_at timestamptz not null default now()
);
create index if not exists share_access_events_owner_time_idx
  on public.share_access_events (owner, accessed_at desc);
create index if not exists share_access_events_token_time_idx
  on public.share_access_events (share_token, accessed_at desc, id desc);
alter table public.share_access_events enable row level security;
revoke all on public.share_access_events from anon, authenticated;
grant select, delete on public.share_access_events to authenticated;
drop policy if exists "share_access_events_select_own" on public.share_access_events;
create policy "share_access_events_select_own" on public.share_access_events
  for select to authenticated using ((select auth.uid()) = owner);
drop policy if exists "share_access_events_delete_own" on public.share_access_events;
create policy "share_access_events_delete_own" on public.share_access_events
  for delete to authenticated using ((select auth.uid()) = owner);
drop policy if exists "share_access_events_mfa_opt_in" on public.share_access_events;
create policy "share_access_events_mfa_opt_in" on public.share_access_events
  as restrictive for all to authenticated
  using (private.session_meets_opt_in_mfa())
  with check (private.session_meets_opt_in_mfa());

-- Anonymous failed attempts are never exposed to the API. They only provide a
-- small per-link throttle so leaked tokens cannot drive unbounded bcrypt work.
create table if not exists public.share_failed_attempts (
  id bigint generated by default as identity primary key,
  share_token uuid not null references public.shares(token) on delete cascade,
  attempted_at timestamptz not null default clock_timestamp()
);
create index if not exists share_failed_attempts_token_time_idx
  on public.share_failed_attempts (share_token, attempted_at desc, id desc);
alter table public.share_failed_attempts enable row level security;
revoke all on public.share_failed_attempts from anon, authenticated;

create or replace function public.create_inventory_share(
  p_label text,
  p_snapshot jsonb,
  p_expires_at timestamptz,
  p_access_code text default null,
  p_max_views integer default null
)
returns uuid
language plpgsql
volatile
security definer
set search_path = pg_catalog, pg_temp
as $$
declare
  v_uid uuid := auth.uid();
  v_token uuid;
  v_code text := nullif(btrim(coalesce(p_access_code, '')), '');
begin
  if v_uid is null then raise exception 'Authentication required' using errcode = '42501'; end if;
  if not private.session_meets_opt_in_mfa() then
    raise exception 'Complete multi-factor authentication before creating a share' using errcode = '42501';
  end if;
  if p_snapshot is null or jsonb_typeof(p_snapshot) <> 'object' then
    raise exception 'Share snapshot must be a JSON object' using errcode = '22023';
  end if;
  if pg_column_size(p_snapshot) > 26214400 then
    raise exception 'Share snapshot exceeds the 25 MB safety limit' using errcode = '22023';
  end if;
  if (p_snapshot ? 'firearms' and jsonb_typeof(p_snapshot->'firearms') <> 'array')
     or (p_snapshot ? 'accessories' and jsonb_typeof(p_snapshot->'accessories') <> 'array') then
    raise exception 'Share item fields must be JSON arrays' using errcode = '22023';
  end if;
  if v_code is not null and (char_length(v_code) < 12 or octet_length(v_code) > 72) then
    raise exception 'Share passcode must be 12 to 72 bytes after trimming' using errcode = '22023';
  end if;
  if p_max_views is not null and (p_max_views < 1 or p_max_views > 10000) then
    raise exception 'Maximum opens must be between 1 and 10000' using errcode = '22023';
  end if;
  if p_expires_at is not null and (p_expires_at <= statement_timestamp()
      or p_expires_at > statement_timestamp() + interval '90 days') then
    raise exception 'Expiry must be within the next 90 days' using errcode = '22023';
  end if;

  insert into public.shares (owner, label, snapshot, expires_at, access_code_hash, max_views)
  values (
    v_uid, nullif(left(btrim(coalesce(p_label, '')), 160), ''), p_snapshot, p_expires_at,
    case when v_code is null then null else extensions.crypt(v_code, extensions.gen_salt('bf', 10)) end,
    p_max_views
  ) returning token into v_token;
  return v_token;
end;
$$;
revoke all on function public.create_inventory_share(text, jsonb, timestamptz, text, integer) from public, anon, authenticated;
grant execute on function public.create_inventory_share(text, jsonb, timestamptz, text, integer) to authenticated;

-- Remove the temporarily ambiguous overloads from the earlier viewer rollout.
drop function if exists public.get_shared_inventory(uuid);
drop function if exists public.get_shared_inventory(uuid, text);

create function public.get_shared_inventory(share_token uuid, share_code text)
returns jsonb
language plpgsql
volatile
security definer
set search_path = pg_catalog, pg_temp
as $$
declare
  v_share public.shares%rowtype;
  v_code text := nullif(btrim(coalesce(share_code, '')), '');
  v_failures integer := 0;
begin
  select * into v_share from public.shares as s where s.token = $1;
  if not found or v_share.revoked_at is not null
     or (v_share.expires_at is not null and v_share.expires_at <= statement_timestamp())
     or (v_share.max_views is not null and v_share.access_count >= v_share.max_views) then
    return null;
  end if;

  if v_share.access_code_hash is not null then
    if v_code is null then
      return jsonb_build_object('requiresCode', true, 'invalidCode', false);
    end if;
    select count(*)::integer into v_failures
    from public.share_failed_attempts
    where share_failed_attempts.share_token = $1
      and attempted_at > clock_timestamp() - interval '15 minutes';
    if v_failures >= 20 then
      return jsonb_build_object('requiresCode', true, 'rateLimited', true);
    end if;
    if octet_length(v_code) > 72
       or extensions.crypt(v_code, v_share.access_code_hash) <> v_share.access_code_hash then
      insert into public.share_failed_attempts (share_token) values ($1);
      delete from public.share_failed_attempts as old
      where old.share_token = $1
        and (old.attempted_at < clock_timestamp() - interval '24 hours' or old.id not in (
          select keep.id from public.share_failed_attempts as keep
          where keep.share_token = $1
          order by keep.attempted_at desc, keep.id desc limit 100
        ));
      return jsonb_build_object('requiresCode', true, 'invalidCode', true);
    end if;
  end if;

  -- Serialize successful opens so the maximum-open counter cannot be raced.
  select * into v_share from public.shares as s where s.token = $1 for update;
  if not found or v_share.revoked_at is not null
     or (v_share.expires_at is not null and v_share.expires_at <= statement_timestamp())
     or (v_share.max_views is not null and v_share.access_count >= v_share.max_views) then
    return null;
  end if;
  update public.shares
  set access_count = access_count + 1, last_accessed_at = clock_timestamp()
  where shares.token = $1;
  insert into public.share_access_events (share_token, owner) values (v_share.token, v_share.owner);
  delete from public.share_failed_attempts where share_failed_attempts.share_token = $1;
  delete from public.share_access_events as old
  where old.share_token = v_share.token and old.id not in (
    select keep.id from public.share_access_events as keep
    where keep.share_token = v_share.token
    order by keep.accessed_at desc, keep.id desc limit 100
  );
  return v_share.snapshot;
end;
$$;
revoke all on function public.get_shared_inventory(uuid, text) from public, anon, authenticated;
grant execute on function public.get_shared_inventory(uuid, text) to anon, authenticated;

create function public.get_shared_inventory(share_token uuid)
returns jsonb
language sql
volatile
security definer
set search_path = pg_catalog, pg_temp
as $$ select public.get_shared_inventory($1, null); $$;
revoke all on function public.get_shared_inventory(uuid) from public, anon, authenticated;
grant execute on function public.get_shared_inventory(uuid) to anon, authenticated;

create or replace function private.cleanup_expired_shares()
returns integer
language plpgsql
volatile
security definer
set search_path = pg_catalog, pg_temp
as $$
declare v_deleted integer;
begin
  with doomed as (
    select token from public.shares
    where expires_at < clock_timestamp() - interval '1 day'
    order by expires_at asc limit 500
  )
  delete from public.shares using doomed where shares.token = doomed.token;
  get diagnostics v_deleted = row_count;
  delete from public.share_failed_attempts where attempted_at < clock_timestamp() - interval '24 hours';
  return v_deleted;
end;
$$;
revoke all on function private.cleanup_expired_shares() from public, anon, authenticated;

-- Require AAL2 for private media only when the account has opted in to MFA.
drop policy if exists "media_mfa_opt_in" on storage.objects;
create policy "media_mfa_opt_in" on storage.objects
  as restrictive for all to authenticated
  using (bucket_id <> 'media' or private.session_meets_opt_in_mfa())
  with check (bucket_id <> 'media' or private.session_meets_opt_in_mfa());

-- If Supabase Cron is enabled, this named job is idempotently created/updated.
do $$
begin
  if exists (select 1 from pg_catalog.pg_extension where extname = 'pg_cron') then
    perform cron.schedule(
      'firearms-vault-expired-share-cleanup',
      '17 4 * * *',
      'select private.cleanup_expired_shares()'
    );
  end if;
exception
  when undefined_function or invalid_schema_name or insufficient_privilege then
    raise notice 'Supabase Cron is not enabled; schedule private.cleanup_expired_shares() after enabling it.';
end;
$$;

commit;
